name: AI Review

on:
  workflow_call:

jobs:

  ai-review:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: AI PR Summary
        uses: Dhana008/java-platform/actions/ai-pr-summary@develop
