name: Platform PR

on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: string
jobs:

  quality:
    uses: Dhana008/java-platform/.github/workflows/java-quality.yml@develop
    with:
      java-version: ${{ inputs.java-version }}

  security:
    uses: Dhana008/java-platform/.github/workflows/codeql.yml@develop
    with:
      java-version: ${{ inputs.java-version }}
